package wsattacker.sso.openid.attacker.gui.discovery.html;

public class HtmlConfigurationGui extends javax.swing.JPanel {

    /**
     * Creates new form XrdsConfigurationGui
     */
    public HtmlConfigurationGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        controller = new wsattacker.sso.openid.attacker.controller.ServerController();
        titel = new javax.swing.JLabel();
        urlLabel = new javax.swing.JLabel();
        urlValue = new javax.swing.JTextField();
        openidServerLabel = new javax.swing.JLabel();
        openIdServerValue = new javax.swing.JCheckBox();
        openId2ProviderLabel = new javax.swing.JLabel();
        openId2ProviderValue = new javax.swing.JCheckBox();
        includeIdentityLabel = new javax.swing.JLabel();
        includeIdentityValue = new javax.swing.JCheckBox();
        includeXrdsHttpHeaderLabel = new javax.swing.JLabel();
        includeXrdsHttpHeaderValue = new javax.swing.JCheckBox();
        includeXrdsHttpHeaderName = new javax.swing.JLabel();
        includeXrdsHttpHeaderNameValue = new javax.swing.JLabel();
        identityLabel = new javax.swing.JLabel();
        identityValue = new javax.swing.JTextField();
        xmlScrollPane = new javax.swing.JScrollPane();
        xml = new javax.swing.JTextPane();

        titel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        titel.setText("HTML Discovery Configuration");

        urlLabel.setText("Base URL:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, controller, org.jdesktop.beansbinding.ELProperty.create("${config.htmlConfiguration.baseUrl}"), urlValue, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        openidServerLabel.setText("Set OpenID Server:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, controller, org.jdesktop.beansbinding.ELProperty.create("${config.htmlConfiguration.openidServer}"), openIdServerValue, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        openId2ProviderLabel.setText("Set OpenID2 Provider:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, controller, org.jdesktop.beansbinding.ELProperty.create("${config.htmlConfiguration.openId2Provider}"), openId2ProviderValue, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        includeIdentityLabel.setText("Include Identity in HTML Document:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, controller, org.jdesktop.beansbinding.ELProperty.create("${config.htmlConfiguration.includeIdentity}"), includeIdentityValue, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        includeXrdsHttpHeaderLabel.setText("Include Identity in XRDS HTTP Header:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, controller, org.jdesktop.beansbinding.ELProperty.create("${config.htmlConfiguration.includeXrdsHttpHeader}"), includeXrdsHttpHeaderValue, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        includeXrdsHttpHeaderName.setText("X-XRDS-Location:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, controller, org.jdesktop.beansbinding.ELProperty.create("${config.htmlConfiguration.identity}"), includeXrdsHttpHeaderNameValue, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        identityLabel.setText("Identity Value:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, controller, org.jdesktop.beansbinding.ELProperty.create("${config.htmlConfiguration.identity}"), identityValue, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        xml.setBackground(getBackground());

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, controller, org.jdesktop.beansbinding.ELProperty.create("${config.htmlConfiguration.html}"), xml, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        xmlScrollPane.setViewportView(xml);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(xmlScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(titel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(openidServerLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(urlLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(openId2ProviderLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(includeIdentityLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(includeXrdsHttpHeaderLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(identityLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(includeIdentityValue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 394, Short.MAX_VALUE))
                            .addComponent(identityValue)
                            .addComponent(urlValue)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(openIdServerValue)
                                    .addComponent(openId2ProviderValue)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(includeXrdsHttpHeaderValue)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(includeXrdsHttpHeaderName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(includeXrdsHttpHeaderNameValue)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlLabel)
                    .addComponent(urlValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openidServerLabel)
                    .addComponent(openIdServerValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openId2ProviderLabel)
                    .addComponent(openId2ProviderValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(includeIdentityLabel)
                    .addComponent(includeIdentityValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(includeXrdsHttpHeaderLabel)
                    .addComponent(includeXrdsHttpHeaderValue)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(includeXrdsHttpHeaderName)
                        .addComponent(includeXrdsHttpHeaderNameValue)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identityLabel)
                    .addComponent(identityValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xmlScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private wsattacker.sso.openid.attacker.controller.ServerController controller;
    private javax.swing.JLabel identityLabel;
    private javax.swing.JTextField identityValue;
    private javax.swing.JLabel includeIdentityLabel;
    private javax.swing.JCheckBox includeIdentityValue;
    private javax.swing.JLabel includeXrdsHttpHeaderLabel;
    private javax.swing.JLabel includeXrdsHttpHeaderName;
    private javax.swing.JLabel includeXrdsHttpHeaderNameValue;
    private javax.swing.JCheckBox includeXrdsHttpHeaderValue;
    private javax.swing.JLabel openId2ProviderLabel;
    private javax.swing.JCheckBox openId2ProviderValue;
    private javax.swing.JCheckBox openIdServerValue;
    private javax.swing.JLabel openidServerLabel;
    private javax.swing.JLabel titel;
    private javax.swing.JLabel urlLabel;
    private javax.swing.JTextField urlValue;
    private javax.swing.JTextPane xml;
    private javax.swing.JScrollPane xmlScrollPane;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
