/*
 * OpenID Attacker
 * (C) 2015 Christian Mainka & Christian Koßmann
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */
package wsattacker.sso.openid.attacker.gui.profile;

import wsattacker.sso.openid.attacker.attack.parameter.AttackParameterKeeper;
import wsattacker.sso.openid.attacker.attack.profile.AttackProfileContainer;

public class ProfileGui extends javax.swing.JPanel {

    /**
     * Creates new form ProfileGui
     */
    public ProfileGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        controller = new wsattacker.sso.openid.attacker.controller.ServerController();
        selectedNameConverter = new wsattacker.sso.openid.attacker.gui.profile.SelectedNameConverter();
        selectedDescriptionConverter = new wsattacker.sso.openid.attacker.gui.profile.SelectedDescriptionConverter();
        title = new javax.swing.JLabel();
        saveLabel = new javax.swing.JLabel();
        saveSeperator = new javax.swing.JSeparator();
        saveNameLabel = new javax.swing.JLabel();
        saveNameValue = new javax.swing.JTextField();
        saveDescriptionLabel = new javax.swing.JLabel();
        saveDescriptionScrollPane = new javax.swing.JScrollPane();
        saveDescriptionValue = new javax.swing.JTextPane();
        saveNewButton = new javax.swing.JButton();
        currentLabel = new javax.swing.JLabel();
        currentSeperator = new javax.swing.JSeparator();
        currentScrollPane = new javax.swing.JScrollPane();
        currentTable = new javax.swing.JTable();
        updateButton = new javax.swing.JButton();
        hint1Label = new javax.swing.JLabel();
        hint2Label = new javax.swing.JLabel();
        loadButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        title.setText("Attack Profiles");

        saveLabel.setText("Save current configuration:");

        saveNameLabel.setText("Name:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, currentTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement}"), saveNameValue, org.jdesktop.beansbinding.BeanProperty.create("text"), "currentlySelectedName");
        binding.setSourceNullValue("New Profile");
        binding.setSourceUnreadableValue("Unreadable");
        binding.setConverter(selectedNameConverter);
        bindingGroup.addBinding(binding);

        saveDescriptionLabel.setText("Description:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, currentTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement}"), saveDescriptionValue, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceNullValue("New Profile description");
        binding.setSourceUnreadableValue("Unreadable");
        binding.setConverter(selectedDescriptionConverter);
        bindingGroup.addBinding(binding);

        saveDescriptionScrollPane.setViewportView(saveDescriptionValue);

        saveNewButton.setText("Save as New");
        saveNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNewButtonActionPerformed(evt);
            }
        });

        currentLabel.setText("Current Configs:");

        currentTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        currentTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${config.profiles.profileList}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, controller, eLProperty, currentTable, "profileList");
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${description}"));
        columnBinding.setColumnName("Description");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        currentScrollPane.setViewportView(currentTable);

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        hint1Label.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        hint1Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hint1Label.setText("Hint: Update also updates Parameters");

        hint2Label.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        hint2Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hint2Label.setText("Hint: Editing Table values does not update Parameters");

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveDescriptionLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveNameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveNameValue)
                    .addComponent(saveDescriptionScrollPane))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(saveSeperator)
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentSeperator)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(currentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(13, 13, 13))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hint1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hint2Label, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveNewButton)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadButton)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {saveNewButton, updateButton});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deleteButton, loadButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveNameLabel)
                    .addComponent(saveNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveDescriptionLabel)
                    .addComponent(saveDescriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveNewButton)
                    .addComponent(updateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hint1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadButton)
                    .addComponent(deleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hint2Label))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void saveNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNewButtonActionPerformed
        String name = saveNameValue.getText();
        String description = saveDescriptionValue.getText();
        AttackParameterKeeper currentConfig = controller.getServer().getParameterConfiguration();
        AttackProfileContainer profiles = controller.getConfig().getProfiles();
        profiles.saveProfile(name, description, currentConfig);
    }//GEN-LAST:event_saveNewButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        int index = currentTable.getSelectedRow();
        String name = saveNameValue.getText();
        String description = saveDescriptionValue.getText();
        AttackParameterKeeper currentConfig = controller.getServer().getParameterConfiguration();
        AttackProfileContainer profiles = controller.getConfig().getProfiles();
        profiles.updateProfile(index, name, description, currentConfig);

    }//GEN-LAST:event_updateButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        int index = currentTable.getSelectedRow();
        AttackParameterKeeper currentConfig = controller.getServer().getParameterConfiguration();
        AttackProfileContainer profiles = controller.getConfig().getProfiles();
        profiles.loadProfile(currentConfig, index);

    }//GEN-LAST:event_loadButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int index = currentTable.getSelectedRow();
        AttackProfileContainer profiles = controller.getConfig().getProfiles();
        profiles.deleteProfile(index);
    }//GEN-LAST:event_deleteButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private wsattacker.sso.openid.attacker.controller.ServerController controller;
    private javax.swing.JLabel currentLabel;
    private javax.swing.JScrollPane currentScrollPane;
    private javax.swing.JSeparator currentSeperator;
    private javax.swing.JTable currentTable;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel hint1Label;
    private javax.swing.JLabel hint2Label;
    private javax.swing.JButton loadButton;
    private javax.swing.JLabel saveDescriptionLabel;
    private javax.swing.JScrollPane saveDescriptionScrollPane;
    private javax.swing.JTextPane saveDescriptionValue;
    private javax.swing.JLabel saveLabel;
    private javax.swing.JLabel saveNameLabel;
    private javax.swing.JTextField saveNameValue;
    private javax.swing.JButton saveNewButton;
    private javax.swing.JSeparator saveSeperator;
    private wsattacker.sso.openid.attacker.gui.profile.SelectedDescriptionConverter selectedDescriptionConverter;
    private wsattacker.sso.openid.attacker.gui.profile.SelectedNameConverter selectedNameConverter;
    private javax.swing.JLabel title;
    private javax.swing.JButton updateButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
